version: '3.7'

services:
  application:
    container_name: nest-events-app
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - nest-events-network
    depends_on:
      - postgres
  postgres:
    container_name: nest-events-db
    image: bitnami/postgresql:latest
    networks:
      - nest-events-network
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: nest-events
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  nest-events-network:
volumes:
  pgdata: